# Generated by Django 5.2.1 on 2025-05-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_alter_customevaluationactivity_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeEstimation',
        ),
    ]
