# Generated by Django 5.2.1 on 2025-05-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0010_rename_semester_fk_to_semester'),
        ('student_portal', '0005_delete_gradeestimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic_data.semester'),
        ),
        migrations.AlterField(
            model_name='semestersummary',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_summaries', to='academic_data.semester'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
