# Generated by Django 5.2.1 on 2025-05-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_remove_duplicate_semester_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='semester',
        ),
    ]
