# Generated by Django 5.2.1 on 2025-05-28 20:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0014_semester_end_date_semester_start_date_and_more'),
        ('student_portal', '0007_remove_semester_from_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='plancomment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='plancomment',
            name='user',
        ),
        migrations.AddField(
            model_name='plancomment',
            name='activity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='comment_type',
            field=models.CharField(choices=[('general', 'General'), ('suggestion', 'Suggestion'), ('question', 'Question'), ('experience', 'Experience'), ('reply', 'Reply')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_portal.plancomment'),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='plan_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('official', 'Official'), ('custom', 'Custom')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_data.studentprofile'),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.plancomment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_data.studentprofile')),
            ],
            options={
                'unique_together': {('comment', 'student')},
            },
        ),
    ]
