# Generated by Django 5.2.1 on 2025-05-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0004_alter_group_id_alter_studentprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='semester',
            field=models.CharField(max_length=20),
        ),
    ]
