# Generated by Django 5.2.1 on 2025-05-28 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0006_add_semester_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='semester_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academic_data.semester'),
        ),
    ]
