# Generated by Django 5.2.1 on 2025-05-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0007_add_semester_fk_to_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('number', 'subject', 'semester_fk')},
        ),
    ]
