# Generated by Django 5.2.1 on 2025-05-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0008_update_group_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='semester',
        ),
    ]
