# Generated by Django 5.2.1 on 2025-05-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0009_remove_semester_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='semester_fk',
            new_name='semester',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('number', 'subject', 'semester')},
        ),
    ]
