# Generated by Django 5.2.1 on 2025-05-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0010_rename_semester_fk_to_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('number', 'subject')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic_data.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic_data.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'program')},
        ),
        migrations.RemoveField(
            model_name='group',
            name='semester',
        ),
    ]
