# Generated by Django 5.2.1 on 2025-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0011_add_program_to_semester'),
    ]

    operations = [
        # First, remove the existing unique_together constraint with 'name'
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),  # Remove all unique_together constraints
        ),
        # Add the new field
        migrations.AddField(
            model_name='semester',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Academic semester number (1, 2, 3, etc.)'),
        ),
        # Update the field properties
        migrations.AlterField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this semester is currently active for enrollment'),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
        # Update model options (but NOT unique_together yet)
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['program', 'number']},
        ),
        # NOTE: unique_together constraint will be added in a separate migration
        # after we migrate the data to have proper semester numbers
    ]
