# Generated by Django 5.2.1 on 2025-05-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0012_alter_semester_options_and_more'),
    ]

    operations = [
    ]
