# Generated by Django 5.2.1 on 2025-05-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_data', '0013_auto_20250528_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'program')},
        ),
    ]
